### PR TITLE
Properly handle spaces in the path of gemset.nix

### LINKED ISSUE #53: bundix -l fails when path has spaces
`bundix -l` is trying to import `gemset.nix`, but failing because there are spaces in the path.

```
[nix-shell:~/main/Personal/Ruby Programs/youtube best]# bundix -l
$ nix-instantiate --eval -E builtins.toJSON(import /root/main/Personal/Ruby Programs/youtube best/gemset.nix)
error: getting status of '/root/main/Personal/Ruby': No such file or directory
Traceback (most recent call last):
	5: from /nix/store/4rq534znwzp27a3y9c81agl30hab9cr6-bundix-2.3.1/bin/.bundix-wrapped:18:in `<main>'
	4: from /nix/store/4rq534znwzp27a3y9c81agl30hab9cr6-bundix-2.3.1/bin/.bundix-wrapped:18:in `load'
	3: from /nix/store/4rq534znwzp27a3y9c81agl30hab9cr6-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/bin/bundix:112:in `<top (required)>'
	2: from /nix/store/4rq534znwzp27a3y9c81agl30hab9cr6-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:33:in `convert'
	1: from /nix/store/4rq534znwzp27a3y9c81agl30hab9cr6-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:79:in `parse_gemset'
/nix/store/4rq534znwzp27a3y9c81agl30hab9cr6-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:122:in `sh': command execution failed: pid 4368 exit 1 (RuntimeError)
```

### PR DESCRIPTION
**Pull request by manveru**
This should fix https://github.com/manveru/bundix/issues/53

### CODE REVIEW

**Review by zimbatm — APPROVED** [review]
LGTM

File: lib/bundix.rb [hunk 1]
```diff
@@ -163,7 +163,7 @@ def parse_gemset
     path = File.expand_path(options[:gemset])
     return {} unless File.file?(path)
     json = Bundix.sh(
-      NIX_INSTANTIATE, '--eval', '-E', "builtins.toJSON(import #{path})")
+      NIX_INSTANTIATE, '--eval', '-E', %(builtins.toJSON (import "#{path}")))
```
Comment (alyssais) [inline lib/bundix.rb:166]: If we use Nixer here, it will handle escaping quotes and stuff too!
